### 1. Extract Data

In [6]:
import requests 

Cities = ["Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"]

listOfCities = []

for city in Cities : 
    url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        "appid": "6a13e61e853763292101962a026aa3e8",
        "q": city
    }
    response = requests.get(url, params=params)
    data = response.json()
    listOfCities.append(data)
    print(data)
    print('---')

{'coord': {'lon': 31.2497, 'lat': 30.0626}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 304.57, 'feels_like': 303.9, 'temp_min': 304.57, 'temp_max': 304.57, 'pressure': 1012, 'humidity': 35, 'sea_level': 1012, 'grnd_level': 1011}, 'visibility': 10000, 'wind': {'speed': 5.14, 'deg': 350}, 'clouds': {'all': 0}, 'dt': 1789736082, 'sys': {'type': 1, 'id': 2514, 'country': 'EG', 'sunrise': 1789702861, 'sunset': 1789747060}, 'timezone': 10800, 'id': 360630, 'name': 'Cairo', 'cod': 200}
---
{'coord': {'lon': 31.2109, 'lat': 30.0081}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 304.56, 'feels_like': 303.31, 'temp_min': 304.56, 'temp_max': 304.56, 'pressure': 1012, 'humidity': 30, 'sea_level': 1012, 'grnd_level': 1009}, 'visibility': 10000, 'wind': {'speed': 3.52, 'deg': 297, 'gust': 9.09}, 'clouds': {'all': 0}, 'dt': 1789736065, 'sys': {'type': 1, 'id': 2514, 'country': 'EG', 'sunrise': 1789702871, 'sunset': 1789747068}, 'timezone': 10800, 'id': 360995, 'name': 'Giza', 'cod': 200}
---
{'coord': {'lon': 29.9553, 'lat': 31.2156}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'base': 'stations', 'main': {'temp': 302.13, 'feels_like': 303.29, 'temp_min': 302.13, 'temp_max': 302.13, 'pressure': 1014, 'humidity': 54, 'sea_level': 1014, 'grnd_level': 1014}, 'visibility': 10000, 'wind': {'speed': 3.09, 'deg': 290}, 'clouds': {'all': 16}, 'dt': 1789736186, 'sys': {'type': 1, 'id': 2511, 'country': 'EG', 'sunrise': 1789703156, 'sunset': 1789747385}, 'timezone': 10800, 'id': 361058, 'name': 'Alexandria', 'cod': 200}
---
{'coord': {'lon': 32.2841, 'lat': 31.2565}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 302.14, 'feels_like': 304.32, 'temp_min': 302.14, 'temp_max': 302.14, 'pressure': 1012, 'humidity': 61, 'sea_level': 1012, 'grnd_level': 1012}, 'visibility': 10000, 'wind': {'speed': 8.23, 'deg': 300}, 'clouds': {'all': 0}, 'dt': 1789736746, 'sys': {'type': 1, 'id': 2522, 'country': 'EG', 'sunrise': 1789702597, 'sunset': 1789746828}, 'timezone': 10800, 'id': 358619, 'name': 'Port Said', 'cod': 200}
---
{'coord': {'lon': 32.5263, 'lat': 29.9737}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 306.33, 'feels_like': 304.96, 'temp_min': 306.33, 'temp_max': 306.33, 'pressure': 1011, 'humidity': 27, 'sea_level': 1011, 'grnd_level': 1002}, 'visibility': 10000, 'wind': {'speed': 4.37, 'deg': 313, 'gust': 9.76}, 'clouds': {'all': 0}, 'dt': 1789736746, 'sys': {'country': 'EG', 'sunrise': 1789702556, 'sunset': 1789746752}, 'timezone': 10800, 'id': 359796, 'name': 'Suez', 'cod': 200}
---
{'coord': {'lon': 32.2723, 'lat': 30.6043}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 307.19, 'feels_like': 308.15, 'temp_min': 307.19, 'temp_max': 307.19, 'pressure': 1011, 'humidity': 38, 'sea_level': 1011, 'grnd_level': 1010}, 'visibility': 10000, 'wind': {'speed': 6.17, 'deg': 310}, 'clouds': {'all': 1}, 'dt': 1789736747, 'sys': {'type': 1, 'id': 2520, 'country': 'EG', 'sunrise': 1789702608, 'sunset': 1789746822}, 'timezone': 10800, 'id': 361055, 'name': 'Ismailia', 'cod': 200}
---
{'coord': {'lon': -1.3394, 'lat': 34.8616}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'base': 'stations', 'main': {'temp': 297.94, 'feels_like': 297.73, 'temp_min': 297.94, 'temp_max': 297.94, 'pressure': 1014, 'humidity': 48, 'sea_level': 1014, 'grnd_level': 953}, 'visibility': 10000, 'wind': {'speed': 3.09, 'deg': 350}, 'clouds': {'all': 16}, 'dt': 1789736545, 'sys': {'type': 1, 'id': 1091, 'country': 'DZ', 'sunrise': 1789710619, 'sunset': 1789754941}, 'timezone': 3600, 'id': 2490183, 'name': 'Mansoûra', 'cod': 200}
---
{'coord': {'lon': 31.0019, 'lat': 30.7885}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'base': 'stations', 'main': {'temp': 305.56, 'feels_like': 304.44, 'temp_min': 305.56, 'temp_max': 305.56, 'pressure': 1012, 'humidity': 30, 'sea_level': 1012, 'grnd_level': 1011}, 'visibility': 10000, 'wind': {'speed': 5.25, 'deg': 311, 'gust': 11.09}, 'clouds': {'all': 50}, 'dt': 1789736185, 'sys': {'country': 'EG', 'sunrise': 1789702911, 'sunset': 1789747129}, 'timezone': 10800, 'id': 347497, 'name': 'Tanta', 'cod': 200}
---
{'coord': {'lon': 32.6421, 'lat': 25.6989}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 312.18, 'feels_like': 310.23, 'temp_min': 312.18, 'temp_max': 312.18, 'pressure': 1010, 'humidity': 16, 'sea_level': 1010, 'grnd_level': 986}, 'visibility': 10000, 'wind': {'speed': 3.6, 'deg': 310}, 'clouds': {'all': 0}, 'dt': 1789736185, 'sys': {'type': 1, 'id': 2516, 'country': 'EG', 'sunrise': 1789702581, 'sunset': 1789746671}, 'timezone': 10800, 'id': 360502, 'name': 'Luxor', 'cod': 200}
---
{'coord': {'lon': 32.907, 'lat': 24.0934}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 314.76, 'feels_like': 312.82, 'temp_min': 314.76, 'temp_max': 314.76, 'pressure': 1009, 'humidity': 14, 'sea_level': 1009, 'grnd_level': 990}, 'visibility': 10000, 'wind': {'speed': 6.17, 'deg': 350}, 'clouds': {'all': 1}, 'dt': 1789736068, 'sys': {'type': 1, 'id': 2526, 'country': 'EG', 'sunrise': 1789702536, 'sunset': 1789746589}, 'timezone': 10800, 'id': 359792, 'name': 'Aswān', 'cod': 200}
---

In [7]:
import pandas as pd

In [11]:
df = pd.DataFrame(listOfCities)
df

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 31.2497, 'lat': 30.0626}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 304.57, 'feels_like': 303.9, 'temp_mi...",10000,"{'speed': 4.63, 'deg': 280}",{'all': 4},1789730534,"{'type': 1, 'id': 2514, 'country': 'EG', 'sunr...",10800,360630,Cairo,200
1,"{'lon': 31.2109, 'lat': 30.0081}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 304.56, 'feels_like': 303.64, 'temp_m...",10000,"{'speed': 3.01, 'deg': 287, 'gust': 8.64}",{'all': 4},1789730945,"{'type': 1, 'id': 2514, 'country': 'EG', 'sunr...",10800,360995,Giza,200
2,"{'lon': 29.9553, 'lat': 31.2156}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 301.13, 'feels_like': 302.25, 'temp_m...",9616,"{'speed': 4.63, 'deg': 280}",{'all': 32},1789730946,"{'type': 1, 'id': 2511, 'country': 'EG', 'sunr...",10800,361058,Alexandria,200
3,"{'lon': 32.2841, 'lat': 31.2565}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 303.14, 'feels_like': 305.57, 'temp_m...",10000,"{'speed': 5.66, 'deg': 280}",{'all': 4},1789730947,"{'type': 1, 'id': 2522, 'country': 'EG', 'sunr...",10800,358619,Port Said,200
4,"{'lon': 32.5263, 'lat': 29.9737}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 305.71, 'feels_like': 304.89, 'temp_m...",10000,"{'speed': 3.99, 'deg': 322, 'gust': 9.2}",{'all': 0},1789730947,"{'country': 'EG', 'sunrise': 1789702556, 'suns...",10800,359796,Suez,200
5,"{'lon': 32.2723, 'lat': 30.6043}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 306.19, 'feels_like': 307, 'temp_min'...",10000,"{'speed': 5.66, 'deg': 350}",{'all': 3},1789730948,"{'type': 1, 'id': 2520, 'country': 'EG', 'sunr...",10800,361055,Ismailia,200
6,"{'lon': -1.3394, 'lat': 34.8616}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 294.94, 'feels_like': 294.66, 'temp_m...",10000,"{'speed': 2.06, 'deg': 350}",{'all': 10},1789730949,"{'type': 1, 'id': 1091, 'country': 'DZ', 'sunr...",3600,2490183,Mansoûra,200
7,"{'lon': 31.0019, 'lat': 30.7885}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 306.13, 'feels_like': 304.86, 'temp_m...",10000,"{'speed': 4.54, 'deg': 305, 'gust': 10.35}",{'all': 52},1789730747,"{'country': 'EG', 'sunrise': 1789702911, 'suns...",10800,347497,Tanta,200
8,"{'lon': 32.6421, 'lat': 25.6989}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 312.18, 'feels_like': 310.68, 'temp_m...",10000,"{'speed': 3.09, 'deg': 360}",{'all': 0},1789730900,"{'type': 1, 'id': 2516, 'country': 'EG', 'sunr...",10800,360502,Luxor,200
9,"{'lon': 32.907, 'lat': 24.0934}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 312.76, 'feels_like': 311.17, 'temp_m...",10000,"{'speed': 6.69, 'deg': 360}",{'all': 0},1789730951,"{'type': 1, 'id': 2526, 'country': 'EG', 'sunr...",10800,359792,Aswān,200

In [18]:
df.drop(columns=['Latitude'])

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 31.2497, 'lat': 30.0626}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 304.57, 'feels_like': 303.9, 'temp_mi...",10000,"{'speed': 4.63, 'deg': 280}",{'all': 4},1789730534,"{'type': 1, 'id': 2514, 'country': 'EG', 'sunr...",10800,360630,Cairo,200
1,"{'lon': 31.2109, 'lat': 30.0081}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 304.56, 'feels_like': 303.64, 'temp_m...",10000,"{'speed': 3.01, 'deg': 287, 'gust': 8.64}",{'all': 4},1789730945,"{'type': 1, 'id': 2514, 'country': 'EG', 'sunr...",10800,360995,Giza,200
2,"{'lon': 29.9553, 'lat': 31.2156}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 301.13, 'feels_like': 302.25, 'temp_m...",9616,"{'speed': 4.63, 'deg': 280}",{'all': 32},1789730946,"{'type': 1, 'id': 2511, 'country': 'EG', 'sunr...",10800,361058,Alexandria,200
3,"{'lon': 32.2841, 'lat': 31.2565}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 303.14, 'feels_like': 305.57, 'temp_m...",10000,"{'speed': 5.66, 'deg': 280}",{'all': 4},1789730947,"{'type': 1, 'id': 2522, 'country': 'EG', 'sunr...",10800,358619,Port Said,200
4,"{'lon': 32.5263, 'lat': 29.9737}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 305.71, 'feels_like': 304.89, 'temp_m...",10000,"{'speed': 3.99, 'deg': 322, 'gust': 9.2}",{'all': 0},1789730947,"{'country': 'EG', 'sunrise': 1789702556, 'suns...",10800,359796,Suez,200
5,"{'lon': 32.2723, 'lat': 30.6043}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 306.19, 'feels_like': 307, 'temp_min'...",10000,"{'speed': 5.66, 'deg': 350}",{'all': 3},1789730948,"{'type': 1, 'id': 2520, 'country': 'EG', 'sunr...",10800,361055,Ismailia,200
6,"{'lon': -1.3394, 'lat': 34.8616}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 294.94, 'feels_like': 294.66, 'temp_m...",10000,"{'speed': 2.06, 'deg': 350}",{'all': 10},1789730949,"{'type': 1, 'id': 1091, 'country': 'DZ', 'sunr...",3600,2490183,Mansoûra,200
7,"{'lon': 31.0019, 'lat': 30.7885}","[{'id': 803, 'main': 'Clouds', 'description': ...",stations,"{'temp': 306.13, 'feels_like': 304.86, 'temp_m...",10000,"{'speed': 4.54, 'deg': 305, 'gust': 10.35}",{'all': 52},1789730747,"{'country': 'EG', 'sunrise': 1789702911, 'suns...",10800,347497,Tanta,200
8,"{'lon': 32.6421, 'lat': 25.6989}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 312.18, 'feels_like': 310.68, 'temp_m...",10000,"{'speed': 3.09, 'deg': 360}",{'all': 0},1789730900,"{'type': 1, 'id': 2516, 'country': 'EG', 'sunr...",10800,360502,Luxor,200
9,"{'lon': 32.907, 'lat': 24.0934}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 312.76, 'feels_like': 311.17, 'temp_m...",10000,"{'speed': 6.69, 'deg': 360}",{'all': 0},1789730951,"{'type': 1, 'id': 2526, 'country': 'EG', 'sunr...",10800,359792,Aswān,200

In [9]:
CitiesData = []

for country in listOfCities:

    CityName = country['name']
    CountryName = country['sys']['country']
    Latitude = country['coord']['lat']
    Longitude = country['coord']['lon']
    Temperature = country['main']['temp']
    Pressure = country['main']['pressure']
    Humidity = country['main']['humidity']
    Windspeed = country['wind']['speed']

    CountryJson = {
        'City': CityName,
        'Country': CountryName,
        'Latitude': Latitude,
        'Longitude': Longitude,
        'Temperature': Temperature,
        'Pressure': Pressure,
        'Humidity': Humidity,
        'Wind Speed': Windspeed
    }

    CitiesData.append(CountryJson)

In [10]:
df = pd.DataFrame(CitiesData)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed
0,Cairo,EG,30.0626,31.2497,304.57,1012,35,5.14
1,Giza,EG,30.0081,31.2109,304.56,1012,30,3.52
2,Alexandria,EG,31.2156,29.9553,302.13,1014,54,3.09
3,Port Said,EG,31.2565,32.2841,302.14,1012,61,8.23
4,Suez,EG,29.9737,32.5263,306.33,1011,27,4.37
5,Ismailia,EG,30.6043,32.2723,307.19,1011,38,6.17
6,Mansoûra,DZ,34.8616,-1.3394,297.94,1014,48,3.09
7,Tanta,EG,30.7885,31.0019,305.56,1012,30,5.25
8,Luxor,EG,25.6989,32.6421,312.18,1010,16,3.60
9,Aswān,EG,24.0934,32.9070,314.76,1009,14,6.17

In [11]:
def classify(city):
    if city == 'Cairo' or city == 'Alexandria':
        return 'Upper'
    else:
        return 'Lower'
df['Region']=df['City'].apply(classify)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region
0,Cairo,EG,30.0626,31.2497,304.57,1012,35,5.14,Upper
1,Giza,EG,30.0081,31.2109,304.56,1012,30,3.52,Lower
2,Alexandria,EG,31.2156,29.9553,302.13,1014,54,3.09,Upper
3,Port Said,EG,31.2565,32.2841,302.14,1012,61,8.23,Lower
4,Suez,EG,29.9737,32.5263,306.33,1011,27,4.37,Lower
5,Ismailia,EG,30.6043,32.2723,307.19,1011,38,6.17,Lower
6,Mansoûra,DZ,34.8616,-1.3394,297.94,1014,48,3.09,Lower
7,Tanta,EG,30.7885,31.0019,305.56,1012,30,5.25,Lower
8,Luxor,EG,25.6989,32.6421,312.18,1010,16,3.60,Lower
9,Aswān,EG,24.0934,32.9070,314.76,1009,14,6.17,Lower

In [12]:
df['Temperature'] = df['Temperature'] - 273.15
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region
0,Cairo,EG,30.0626,31.2497,31.42,1012,35,5.14,Upper
1,Giza,EG,30.0081,31.2109,31.41,1012,30,3.52,Lower
2,Alexandria,EG,31.2156,29.9553,28.98,1014,54,3.09,Upper
3,Port Said,EG,31.2565,32.2841,28.99,1012,61,8.23,Lower
4,Suez,EG,29.9737,32.5263,33.18,1011,27,4.37,Lower
5,Ismailia,EG,30.6043,32.2723,34.04,1011,38,6.17,Lower
6,Mansoûra,DZ,34.8616,-1.3394,24.79,1014,48,3.09,Lower
7,Tanta,EG,30.7885,31.0019,32.41,1012,30,5.25,Lower
8,Luxor,EG,25.6989,32.6421,39.03,1010,16,3.60,Lower
9,Aswān,EG,24.0934,32.9070,41.61,1009,14,6.17,Lower

In [13]:
df.isna().sum()

City           0
Country        0
Latitude       0
Longitude      0
Temperature    0
Pressure       0
Humidity       0
Wind Speed     0
Region         0
dtype: int64

In [14]:
def classifyTemp(temp): 
    if temp <= 25: 
        return 'Cold'
    elif 25<temp<=30:
        return 'Moderate'
    elif temp>30: 
        return 'Hot' 
df['Temperature Category'] = df['Temperature'].apply(classifyTemp)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region,Temperature Category
0,Cairo,EG,30.0626,31.2497,31.42,1012,35,5.14,Upper,Hot
1,Giza,EG,30.0081,31.2109,31.41,1012,30,3.52,Lower,Hot
2,Alexandria,EG,31.2156,29.9553,28.98,1014,54,3.09,Upper,Moderate
3,Port Said,EG,31.2565,32.2841,28.99,1012,61,8.23,Lower,Moderate
4,Suez,EG,29.9737,32.5263,33.18,1011,27,4.37,Lower,Hot
5,Ismailia,EG,30.6043,32.2723,34.04,1011,38,6.17,Lower,Hot
6,Mansoûra,DZ,34.8616,-1.3394,24.79,1014,48,3.09,Lower,Cold
7,Tanta,EG,30.7885,31.0019,32.41,1012,30,5.25,Lower,Hot
8,Luxor,EG,25.6989,32.6421,39.03,1010,16,3.60,Lower,Hot
9,Aswān,EG,24.0934,32.9070,41.61,1009,14,6.17,Lower,Hot

In [16]:
def classifyHumd(humd):
    if humd <=30: 
        return "Low"
    elif humd <=45:
        return "Moderate"
    elif humd >45: 
        return "High"
df['Humidity Category'] = df['Humidity'].apply(classifyHumd)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region,Temperature Category,Humidity Category
0,Cairo,EG,30.0626,31.2497,31.42,1012,35,5.14,Upper,Hot,Moderate
1,Giza,EG,30.0081,31.2109,31.41,1012,30,3.52,Lower,Hot,Low
2,Alexandria,EG,31.2156,29.9553,28.98,1014,54,3.09,Upper,Moderate,High
3,Port Said,EG,31.2565,32.2841,28.99,1012,61,8.23,Lower,Moderate,High
4,Suez,EG,29.9737,32.5263,33.18,1011,27,4.37,Lower,Hot,Low
5,Ismailia,EG,30.6043,32.2723,34.04,1011,38,6.17,Lower,Hot,Moderate
6,Mansoûra,DZ,34.8616,-1.3394,24.79,1014,48,3.09,Lower,Cold,High
7,Tanta,EG,30.7885,31.0019,32.41,1012,30,5.25,Lower,Hot,Low
8,Luxor,EG,25.6989,32.6421,39.03,1010,16,3.60,Lower,Hot,Low
9,Aswān,EG,24.0934,32.9070,41.61,1009,14,6.17,Lower,Hot,Low

In [17]:
import datetime 
date = datetime.datetime.now().strftime('%Y-%m-%d')

In [18]:
date = datetime.datetime.now().strftime('%Y-%m-%d')

df['Ingestion Time'] = date
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region,Temperature Category,Humidity Category,Ingestion Time
0,Cairo,EG,30.0626,31.2497,31.42,1012,35,5.14,Upper,Hot,Moderate,2026-09-18
1,Giza,EG,30.0081,31.2109,31.41,1012,30,3.52,Lower,Hot,Low,2026-09-18
2,Alexandria,EG,31.2156,29.9553,28.98,1014,54,3.09,Upper,Moderate,High,2026-09-18
3,Port Said,EG,31.2565,32.2841,28.99,1012,61,8.23,Lower,Moderate,High,2026-09-18
4,Suez,EG,29.9737,32.5263,33.18,1011,27,4.37,Lower,Hot,Low,2026-09-18
5,Ismailia,EG,30.6043,32.2723,34.04,1011,38,6.17,Lower,Hot,Moderate,2026-09-18
6,Mansoûra,DZ,34.8616,-1.3394,24.79,1014,48,3.09,Lower,Cold,High,2026-09-18
7,Tanta,EG,30.7885,31.0019,32.41,1012,30,5.25,Lower,Hot,Low,2026-09-18
8,Luxor,EG,25.6989,32.6421,39.03,1010,16,3.60,Lower,Hot,Low,2026-09-18
9,Aswān,EG,24.0934,32.9070,41.61,1009,14,6.17,Lower,Hot,Low,2026-09-18

In [19]:
data = list(df.itertuples(index = None, name = None))

In [22]:
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)
 
curosr = conn.cursor()
curosr.execute("""
               create table SeifWeatherData (
    id int identity(1,1) primary key,
    City varchar(50),
    Country varchar(50),
    Latitude varchar(50),
    Longitude varchar(50),
    Temperature varchar(50),
    Pressure varchar(50),
    Humidity varchar(50),
    [Wind Speed] varchar(50),
    Region varchar(50),
    [Temperature Category] varchar(50),
    [Humidity Category] varchar(50),
    [Ingestion Time] varchar(50)
);
""")
curosr.commit()      
curosr.close()
conn.close()

ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'SeifWeatherData' in the database. (2714) (SQLExecDirectW)")

In [24]:
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)
cursor = conn.cursor()

cursor.executemany("""
    insert into SeifWeatherData
    values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", data)

conn.commit()

cursor.close()
conn.close()